NO_CORE         = Yes
F_CPU           = 16000000L
BOARD_TAG       = atmega328p
MCU             = atmega328p
ARDUINO_DIR     = /home/pi/arduino
ISP_PROG        = usbasp

include /home/pi/Arduino-Makefile/Arduino.mk