F_CPU               = 16000000
BOARD_TAG           = uno
MCU                 = atmega328p
ARDUINO_DIR         = /home/pi/arduino-1.6.7
ISP_PROG            = usbasp
USER_LIB_PATH       = ../lib
ARDUINO_LIBS        = LiquidCrystal TwiscnUSB
AVR_TOOLS_DIR       = /usr
AVRDUDE             = /usr/bin/avrdude
AVRDUDE_CONF        = /etc/avrdude.conf

include /home/pi/Arduino-Makefile/Arduino.mk