F_CPU           = 16000000L
BOARD_TAG       = uno
MCU             = atmega328p
ARDUINO_DIR     = /home/pi/arduino-1.6.7
ISP_PROG        = usbasp
ARDUINO_LIBS    = LiquidCrystal
AVR_TOOLS_DIR   = /usr
AVRDUDE         = /usr/bin/avrdude
AVRDUDE_CONF    = /etc/avrdude.conf

include /home/pi/Arduino-Makefile/Arduino.mk